# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b32fe4e64fb6a23c1c3eb36e5ea57b50bc0d1ad7587b761243aa2295f5eb73cf3df638f77c623eadac41f2fb4127ec78c6977a42f56619cb20eb4ab8c50e3d5

test:
  secret_key_base: 83f08fa97c5e7582587f46a9e5bfc863bb32961f97cf281dec76d19e54c499f25d059dce689be9b78730cd384361361933e33cd4595d10f786a5dc7a870cb9b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
